### ISSUE TITLE
Fix add more than one device

### ISSUE THREAD

**Issue by valentincre** [MeisApps/pcbu-desktop-old#4]
Hello everyone,
First of all, thanks for this really cool app!

I'm having a problem with the new feature for adding multiple devices. In fact I have two identical phones and if I want to pair both, when I pair the second it deletes the first in the `paired_device.json` file. This is due to the identifier being identical. I saw that this identifier was created on [this line](https://github.com/MeisApps/pcbu-desktop/blob/a88fffd0345891782e153dd8e23a382d2b0ec86b/src/main/kotlin/com/meisapps/pcbiounlock/server/pairing/PairingServer.kt#L75). 
I can't change this `NativeUtils.getForPlatform().getDeviceUUID()` and this `userData.userName` as it matches data on my computer, but I've tried putting a different phone name on each device to try and change this `packet.deviceName`. Unfortunately, for some reason the name recorded in the `paired_device.json` file remains the same.

One possible solution is to find the real name of the device or to use a more unique data so that I can have different identifiers.

Have a good day and don't hesitate to contact me if you have any questions.

**Comment by MeisApps** [comment]
Hi,

it is fixed in the latest version (1.5.3). Now a random UUID is generated for each app install and used for the pairing ID.
Don't forget to rate the app ;)

Best regards,
Meis Apps
